extends:
  - vazco/typescript

rules:
  '@typescript-eslint/no-explicit-any': 0
  '@typescript-eslint/explicit-function-return-type': 0
  '@typescript-eslint/ban-ts-ignore': 0
  react/prop-types: 0
  valid-jsdoc: 0
  'vazco/no-console': 0
