ARG NODE=12-alpine

FROM node:$NODE AS nodeDeps
WORKDIR /app
ENV HUSKY_SKIP_INSTALL=1

COPY package.json yarn.lock tsconfig.json  ./
COPY client ./client

RUN yarn install
RUN yarn workspace client build

FROM nginx:1.17.1-alpine
RUN \
    apk update &&\
    apk add tini
WORKDIR ./app

COPY --from=nodeDeps ./app/node_modules ./node_modules
COPY --from=nodeDeps /app/client/nginx/nginx.conf /etc/nginx/conf.d/default.conf
COPY --from=nodeDeps /app/client/build /usr/share/nginx/html
