version: "3.8"

services:
  server:
    build:
      context: .
      dockerfile: Dockerfile.server
    ports:
    - "5000:5000"
    networks:
      local:
    environment:
      MONGO_URI: "mongodb://mongo:27017/callbetterDB"
      JWT_SECRET: "v8k2virBgSox2C4PFJ0WmbyTYIXu16eTjSAvVvB4E0Sgj8XvBn"
  mongo:
    image: mongo
    volumes:
      - db:/data/db
    networks:
      local:
        aliases:
          - mongo
  react:
    build:
      context: .
      dockerfile: Dockerfile.client
    ports:
      - "3000:80"
    networks:
      local:



networks:
  local:

volumes:
  db:
